### ISSUE TITLE
Form data shows in the address bar

### ISSUE THREAD

**Issue by Fakka** [creativetimofficial/now-ui-kit#1]
I'm trying to create a signin/signup form using PHP. And anytime I hit on the submit button instead of submitting the data shows up in the address bar.
sorry for me bad english
![now_ui_kit](https://cloud.githubusercontent.com/assets/10529817/26513813/7fd64d8a-4265-11e7-87f9-1d8811dea17f.png)

**Comment by Francismori7** [comment]
```<form [...] method="post">```

**Comment by alexandru-paduraru** [comment]
@Fakka please check how the HTML forms work here: https://www.w3schools.com/html/html_forms.asp and use the suggestion of @Francismori7 to fix your issue.

Best,
Alex
