### ISSUE TITLE
consider using a less suggestive avatar stock photo

### ISSUE THREAD

**Issue by wbolster** [creativetimofficial/now-ui-kit#10]
first of all, thanks for publishing this great looking project under such a liberal license.

that said, please consider using a less suggestive avatar stock photo for the [image section on the sample page](http://demos.creative-tim.com/now-ui-kit/index.html#images).

my first reaction when scrolling down that page was "geez, why the f^@# is this dude called tim using a picture of a naked woman. so immature and sexist."  (yes, i know tim is the agency name.)

after a quick google image search i figured out this is a free "do whatever you want" stock photo by @araltasher from their [unsplash portfolio](https://unsplash.com/@araltasher), more specifically [this photo](https://unsplash.com/@araltasher?photo=vBumGhXdgTE), which does not feature any nudity, which proved my initial reaction was "wrong". that said, the cropping suggests otherwise, at least to me upon first glance.

anyway, i am sure none of this is intentional so i am not calling out anyone here. i just want to share my reaction when looking at that otherwise very nice demo page, hence this message.

keep up the good work, but please reconsider the stock photo. :)

**Comment by Pitu** [comment]
I don't really see how the stock image on the sample page could be considered suggestive. I believe that immature and sexist is the fact that you consider a perfectly normal profile picture of a woman to be suggestive. Chill down, it's just a photo.

**Comment by wbolster** [comment]
sadly, i got this comment which was later deleted apparently. i am not here to let someone who did not even read my message accuse me of the thing i am actually pointing out _without_ pointing fingers (since i did not intend to do that as i wrote above). closing this issue since i have no energy for this nonsense. i do not care anymore.

![2017-06-11 14 14 34](https://user-images.githubusercontent.com/748944/27010940-9f636dc0-4eb0-11e7-9a70-36896aae63a9.jpg)

**Comment by alexandru-paduraru** [comment]
@wbolster here is Alex, the co-founder of creative-tim.com. Thank you for pointing that out, now if we check it again it is looking like the girl is naked, we didn't have this in our mind when we added her. We will change that image on the next released.

Best,
Alex

**Comment by wbolster** [comment]
thanks, great response, alex. i didn't assume it was intentional, good to hear that confirmed. thanks!

(oh and sorry for me being grumpy about random ppl on the internet not affiliated to you in any way on your bug tracker.)

**Comment by Pitu** [comment]
Sorry about that. After commenting I realized it's not my business and getting involved would be a waste of time since this is the internet so I proceeded to delete my comment. Didn't mean to disrespect you, it just seemed to me you were after something that wasn't there. 
Sorry for troubling you.

**Comment by wbolster** [comment]
@pitu ok seems we agree to disagree. i will delete my previous comment with the screenshot of your deleted cinema to not leave an ugly trail here.

**Comment by wbolster** [comment]
awesome, thanks @alexandru-paduraru
