### ISSUE TITLE
Now UI Kit link in readme goes to Material Kit Pro demo page.

### ISSUE THREAD

**Issue by DavidEBest** [creativetimofficial/now-ui-kit#12]
The text link to 'Now UI Kit' in README.md body goes to 'http://demos.creative-tim.com/material-kit-pro/index.html'. The header link correctly goes to 'http://demos.creative-tim.com/now-ui-kit/index.html'.

**Comment by alexandru-paduraru** [comment]
@DavidEBest thank you for pointing out. Just fixed it: https://github.com/creativetimofficial/now-ui-kit/blob/master/README.md

Best,
Alex
