### ISSUE TITLE
Modal content issue

### ISSUE THREAD

**Issue by arpit016** [creativetimofficial/now-ui-kit#15]
When the modal content increases to the point when it becomes scrollable, the modal just shifts way down the page when launched.
![modal_shifts_way_down](https://user-images.githubusercontent.com/13781801/27297988-9999fb4e-5544-11e7-9984-7190deb44dd6.PNG)

As you can see in the screenshot above when I increased the content the modal just shifted way down to the page. I tried this in the example pages that comes with nowuikit when downloaded. Whereas in bootstrap4 docs and example on their website the modal works fine for longer content. Please look into this.

**Comment by arpit016** [comment]
I believe it's happening because of below piece of CSS code inside nowui:
`.modal.show .modal-dialog {
  -webkit-transform: translate(0, 30%);
  -o-transform: translate(0, 30%);
  transform: translate(0, 30%); 
}`

When I changed the value from 30% to 0 the shifting disappeared. Kindly look into this and release a fix for it in your next version. For now I am overriding it for my project.

**Comment by alexandru-paduraru** [comment]
@arpit016 thank you for pointing that out. We will check and see why we added that property. If it just changing something and is not helping us we will remove it.

**Comment by finkbg** [comment]
+1 - we are also having this issue, so we had to use modal-mini instead. Now our pop-up images, which are supposed to be a zoomed-in view are actually smaller than the thumbnails :)

**Comment by arpit016** [comment]
@finkbg you can modify the percentage in the below piece of code inside nowuikit css file:
`.modal.show .modal-dialog { -webkit-transform: translate(0, 30%); -o-transform: translate(0, 30%); transform: translate(0, 30%); }
`
There is no need to use modal mini for you. Just update the percentage value to somewhere between 1% to 5% and you can use the normal modal. Just experiment what percentage goes with your content and set it to that percentage.
