### ISSUE TITLE
incompatible units rem and px

### ISSUE THREAD

**Issue by opichon** [creativetimofficial/now-ui-kit#17]
When loading now-ui-kit.scss via webpack with bootstrap.scss, the following error occurs:

```
Module build failed:
$input-height:                   (($font-size-base * $input-line-height) + ($input-padding-y * 2)) !default;
                                ^
      Incompatible units: 'rem' and 'px'.
      in /Users/olivier/projects/vuejs/vuemedium/node_modules/bootstrap/scss/_variables.scss (line 444, column 34)
```
According to bootstrap [https://github.com/twbs/bootstrap-sass/issues/1057] this is most likely an errors in your ui kit, not bootstrap. It seems that you are using px units in some variables. 

I believe a big aspect of bs4 was the use of rem units! Using px (or even em) units in your ui kit seems to defeat the purpose.

**Comment by cristijora** [comment]
I got the same error when trying to use the sass files with webpack. I fixed it by changing `font-size-base` to rem units as well as other variables which caused similar errors. I think that's something that should be done in the kit also

**Comment by yesh0907** [comment]
Can you explain why does switching to rem units work? It doesn't make sense to me.

**Comment by wallysonn** [comment]
I can not explain the reason, but when I replaced the variables by their respective values, it worked. See: 
`$input-height: ((1rem * 1.25) + (.5rem * 2))! Default;`
