### ISSUE TITLE
Mobile view navbar dropdown error

### ISSUE THREAD

**Issue by postituvi** [creativetimofficial/now-ui-kit#18]
When adding to the navbar dropdown menu, the mobile view sees the submenu space but not the text. The first image shows the menu when clicked to the hamburger, the second when expanded the topic "Klubi"
![1](https://user-images.githubusercontent.com/21066829/27553871-511513d8-5ab5-11e7-919e-c284c387f6c7.png)
![2](https://user-images.githubusercontent.com/21066829/27553870-51149bf6-5ab5-11e7-93d1-6550a452678c.png)

**Comment by elraghifary** [comment]
Hi, sorry cannot reply your question.

But, how to change navbar toggle color to blue? Default was orange.

**Comment by dragosct10** [comment]
Hi @postituvi! Sorry for the late response. For fixing the issue with the dropdown on the mobile view please take the uploaded `_responsive.scss` partial and go in `assets/sass/now-ui-kit/_responsive.scss` and replace with the new one. Please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/now-ui-kit.css`. Please let us know if everything is working fine! 

[_responsive.scss.zip](https://github.com/creativetimofficial/now-ui-kit/files/1138279/_responsive.scss.zip)

Regards,
Dragos

**Comment by jcesarg** [comment]
Hello I had the same problem but when compile they had error.

I you can help me, thanks.

**Comment by alexandru-paduraru** [comment]
@jcesarg please make sure the settings for Koala are like this:

<img width="201" alt="screen shot 2017-07-25 at 11 02 01" src="https://user-images.githubusercontent.com/2517758/28561860-c2947bb4-7128-11e7-9ade-dc53a69a756e.png">

Best,
Alex

**Comment by jcesarg** [comment]
Sorry for the disturbances, but I have the same error,.

**Comment by alexandru-paduraru** [comment]
What error?

**Comment by jcesarg** [comment]
This error, I see tutorials, videos and nothing

![screen](https://user-images.githubusercontent.com/6981459/28839567-ac378168-76b9-11e7-9960-c5aa57fbac23.png)

**Comment by alexandru-paduraru** [comment]
@jcesarg unfortunately I don't know what the message says as I don't know italian/spanish. Maybe you can try to use the Gulp + Gulp-Sass: https://www.npmjs.com/package/gulp-sass to compile your sass.
