### ISSUE TITLE
Can't resolve '../fonts/nucleo-outline.svg'

### ISSUE THREAD

**Issue by switmac** [creativetimofficial/now-ui-kit#21]
Hello all,

the now-ui-kit.css breaks since it can't find the 'nucleo-outline.svg' in the fonts folder. :)

installed this using `npm install`

thanks..

**Comment by alexandru-paduraru** [comment]
@switmac thank you for the information, we need to remove that line from the SASS and CSS because we are not using svg icons, just the font. We will do this in the next update. Thank you for pointing out!

**Comment by switmac** [comment]
Thank you @alexandru-paduraru, looking forward to your next release and thanks for sharing your great works. :)

**Comment by nuttikung** [comment]
I fixed it by comment .svg (I use scss version) >> assets/sass/now-ui-kit/_nucleo-outline.scss
Line 
15 >>  url('../fonts/nucleo-outline.ttf') format('truetype');
16 >>  // url('../fonts/nucleo-outline.svg') format('svg');

That's work for me.

**Comment by bumxu** [comment]
Also, these lines maybe need to use the `$nc-font-path` variable.

Great work. ;)

**Comment by alec-c4** [comment]
hi @timcreative! the same error for paper kit 2 pro

**Comment by cregx** [comment]
The issue is still there in **Now-UI-Kit-Pro v. 1.2.0** and should be fixed to save the time.

**Comment by dragosct10** [comment]
Hi! Thank you for using our product. We will fix this in the next update of the product which will be in about 1-2 weeks. Regards, Dragos

**Comment by KimSoungRyoul** [comment]
I have same problem... in Paper Kit 2 PRO 1.2.0

**Comment by ndanielsen** [comment]
Same problem in Paper Kit 2 PRO and Paper Kit 2 React Dashboard

**Comment by ndanielsen** [comment]
Just placing this here as this was the fix for my problem, it was an s3 cors issue:

https://stackoverflow.com/questions/12229844/amazon-s3-cors-cross-origin-resource-sharing-and-firefox-cross-domain-font-loa

**Comment by sylvainR37** [comment]
Hi, I see the same problem. If I look at the repository, I see the correction commit but when I use "yarn add paper-dashboard-2", I do not have the correction in my "node_modules" folder. Why ?
