### ISSUE TITLE
Wrong h5 tag close 

### ISSUE THREAD

**Issue by kalidiagne** [creativetimofficial/now-ui-kit#22]
Hi, using this UI Kit with VueJS it give me a syntax error:
At line 1076 in index.html
`<h5 class="description">The kit comes with three pre-built pages to help you get started faster. You can change the text and images and you're good to go. More importantly, looking at them will give you a picture of what you can built with this powerful Bootstrap 4 ui kit.</h4>`

**Comment by alexandru-paduraru** [comment]
@klddiagne thank you for pointing out. We will fix that in the next release. Please replace the h4 with h5 and everything should work fine.

Best,
Alex

**Comment by klddiagne** [comment]
@alexandru-paduraru yeah i do it, and works fine! great job!

**Comment by cristijora** [comment]
@klddiagne There will also be a pure vue version coming out based on this kit. It is still early in development but to get an idea, you could take a look https://cristijora.github.io/vue-now-ui/#/en-US/component/button
