### ISSUE TITLE
Mobile menu on all media sreens

### ISSUE THREAD

**Issue by cegascam** [creativetimofficial/now-ui-kit#24]
Hi to  everyone, i want to use the mobile menu on all the media sreen not only at the mobile ones. To do that i modified the css to make the "navbar-toggler" button allways visible as block and i modified the now-ui-kit.css file at the line 3469, the 991 media screen, and set it to @media screen and (max-width: 150000px) . And i thought it had worked perfectly, but now i realize it doesn't. 
I load the page, and if i click on the navbar-toggler the "nav-open" class doesn't appear at the html tag. BUT, if i resize the browser screen to a movile size it works (as expected), AND if i rezise the browser to the desktop resolutions everything works great!!!.

**Comment by cegascam** [comment]
Thanks for the answer, do you have any idea about the release date of the v1.1.0?

**Comment by alexandru-paduraru** [comment]
@cegascam it should come around 15 August :D
