### ISSUE TITLE
DateTime Picker in Firefox

### ISSUE THREAD

**Issue by punshonjm** [creativetimofficial/now-ui-kit#25]
When trying top use the Now UI Kit I have come across an issue with the Date Picker element. 
Setup like in the demo, the back and forward buttons on the calendar do not work. The same issue happens with clicking the Month, which should zoom out to show month-on-month view, and then zoom to years. 

The issue does not happen in Chrome, I am testing in Firefox 54.0.1
I tried it with all add-ons disabled, same effect. 

The issue also exists on the demo site: 
http://demos.creative-tim.com/now-ui-kit/documentation/tutorial-components.html#datepicker-row

But does not exists when testing on http://www.eyecon.ro/bootstrap-datepicker/ in Firefox.

**Comment by punshonjm** [comment]
Issue seems to be caused by z-index, create PR #26

**Comment by alexandru-paduraru** [comment]
@punshonjm you're right, thank you for the PR, we will integrate it in the next update.

Best,
Alex
