### ISSUE TITLE
React support!

### ISSUE THREAD

**Issue by Shashwatsh** [creativetimofficial/now-ui-kit#27]
how do I use it with React.js (when react is installed via npm) ?

**Comment by alexandru-paduraru** [comment]
@Shashwatsh unfortunately, at this moment, we don't have experience with React. There is a WIP version of React for Material Kit and it is built by one of our collaborators: https://github.com/creativetimofficial/material-kit-react. Maybe you can check that version and see how it is structured and you can add the CSS/JS from the Now UI kit.

Best,
Alex

**Comment by yesh0907** [comment]
@Shashwatsh I [created an implementation](https://github.com/yesh0907/Now-UI-Kit-React) of Now UI Kit in React. I am still developing it but it would be really kind of you to help me test all the components. So far I am aware that the slider doesn't work. Also if you would like to help just create a PR and I will take a look at it ASAP. Cheers 🍺

**Comment by mcquiggd** [comment]
@yesh0907 

You might have fixed this and not committed yet... but your current Github repo is missing a dependency,  Popper.js

`npm install popper.js --save-dev`

in src/index.js, before the line:

`require('bootstrap'); `

add the following (needs to be umd):

`require('popper.js/dist/umd/popper');`


In the cfg/dev.js and  cfg/dist.js

Add the following to the webpack.ProvidePlugin configuration

`Popper: 'popper.js'`

Then:

npm run dist

npm start

**Comment by mcquiggd** [comment]
I like this theme - I might try to make a React version that would work with `create-react-app`.

**Comment by yesh0907** [comment]
@mcquiggd Made the fix. I originally tried to use create-react-app but was not having much success with it. If you do manage to figure it please let me know. Thanks for the help!

**Comment by mcquiggd** [comment]
@yesh0907 

Since posting above, I have begun focusing on Vue rather than React (a month is a long time in Web Dev), but I will update here if I have time to look at a React version.

**Comment by Shashwatsh** [comment]
Any updates on this?
