### ISSUE TITLE
Check mark not working

### ISSUE THREAD

**Issue by dylanm21** [creativetimofficial/now-ui-kit#28]
Hi I'm very confused. I compiled scss and now i'm having this error when i debug:

SyntaxError: expected expression, got '.'[Learn More]  now-ui-kit.css:28
line 28 starts with 
.bootstrap-switch {

**Comment by dylanm21** [comment]
Nvm I got it

**Comment by alexandru-paduraru** [comment]
@dylanm21 glad that it is working, I will close this :D
