### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by dylanm21** [creativetimofficial/now-ui-kit#29]
Hi I'm having trouble with the check box. When i check the box, there is no check mark, just an "error" image
![screen shot 2017-07-23 at 7 30 48 pm](https://user-images.githubusercontent.com/10284654/28503978-7b4ea834-6fdd-11e7-91db-2b35204fdc83.png)

Any ideas?

**Comment by alexandru-paduraru** [comment]
@dylanm21 do you have a link that we can check?

**Comment by dylanm21** [comment]
Sorry just seeing this, yes here is the link:
https://flashmanwade.co/my-account/

The "remember me" checkbox

**Comment by alexandru-paduraru** [comment]
@dylanm21 please make sure you included the fonts folder as it is included in the original archive:

<img width="838" alt="screen shot 2017-07-27 at 09 44 10" src="https://user-images.githubusercontent.com/2517758/28657533-4794dd08-72b0-11e7-9afb-bcc8dbd68f13.png">

Best,
Alex

**Comment by dylanm21** [comment]
Hmm I thought it is included? 
It looks like the check mark uses this:

<img width="442" alt="screen shot 2017-07-30 at 12 18 47 am" src="https://user-images.githubusercontent.com/10284654/28750556-e5208618-74bc-11e7-8b74-2fd4fd1eb2fe.png">

and when I go to 
https://flashmanwade.co/wp-content/themes/flashman/assets/fonts/nucleo-outline.woff2

It pulls up an option to download the font, which means it is included in the correct file structure. I'm a bit confused now.

**Comment by alexandru-paduraru** [comment]
@dylanm21 don't know how Wordpress handle those files, but on our UI Kit and also in the archive that you downloaded everything is there and working fine. Try to add absolute paths, like the whole link that you gave me, maybe it doesn't know how to work with relative paths like "../fonts..." maybe some Wordpress users can help better :D

**Comment by dylanm21** [comment]
Cool, I'll double check everything, thanks!
