### ISSUE TITLE
Change clear-filter color from orange to ...?

### ISSUE THREAD

**Issue by finkbg** [creativetimofficial/now-ui-kit#30]
As the title suggests, there is now way to easily change the filter-color from orange to something else.

I might as well make a general suggestion:

Why don't you get rid of "orange" in scss/html, name it primary color and make it conform to the $primary-color variable? For example, if I set my primary color as blue, I should be able to set filter-color="primary", have a blue fade and call it a day. Do you think this makes sense?

**Comment by alexandru-paduraru** [comment]
@finkbg thank you for the suggestion. We have in plan to add more colors, like red, blue, green, purple etc. but the best way would be to have this synced with primary, success, warning etc. So this makes sense. This will come first in the PRO version, then in the Free.

**Comment by finkbg** [comment]
Any progress here?
