### ISSUE TITLE
Can not change switch/toggle buttons size

### ISSUE THREAD

**Issue by sangdth** [creativetimofficial/now-ui-kit#31]
I'm using NowUI 1.0.0, after check your css file, I saw some predefine classes for toggle button like: `bootstrap-switch-mini`, `bootstrap-switch-small`, `bootstrap-switch-large` but it does not take any effect at all.

**Comment by alexandru-paduraru** [comment]
@sangdth thank you for the information. This bug is confirmed. We will fix this in the next release.
