### ISSUE TITLE
Safari login page

### ISSUE THREAD

**Issue by Jorgu5** [creativetimofficial/now-ui-kit#37]
Hey,

Example login page on safari is completely out of style. That's because of using 100vh which safari is not supporting yet. Suggesting to add height 100% to html, body and then to page-header in order to handle it within all the browsers properly.

**Comment by alexandru-paduraru** [comment]
@Jorgu5 thank you for using our product. Here is what we have in Safari Version 10.0 (12602.1.50.0.10) on Mac Sierra.

<img width="1440" alt="screen shot 2017-08-22 at 15 46 19" src="https://user-images.githubusercontent.com/2517758/29566070-261aa68e-8751-11e7-95ea-0f3e9c90d8d7.png">

Can you please let us know which version are you using and what OS?

Best,
Alex

**Comment by peiche** [comment]
@Jorgu5 Maybe, as a fallback, set the height to something like 500px first, in case the vh statement fails:

```
height: 500px;
height: 100vh;
```
