### ISSUE TITLE
Any way to have a navbar with some buttons on the left and some to the right ?

### ISSUE THREAD

**Issue by MorenaDaniel** [creativetimofficial/now-ui-kit#42]
Hi !

I would like to know if it's possible to have a navbar that have the navbar-brand then some buttons just next to it, and then some buttons on the far right. I saw that there is a class Justify-content-end that i can change to Justify-content-left to have my buttons on the left, but i don't find a way to put the Justify-content-end for the last 3 buttons.

Here is an exemple of what i would like to achieve

![exemple](https://user-images.githubusercontent.com/7815280/30444734-34667f7a-9984-11e7-97d2-e3aed10442ac.jpg)

Thx for the help

**Comment by alexandru-paduraru** [comment]
@MorenaDaniel thank you for using our product. Please check the official documentation from Bootstrap about navbar elements: https://getbootstrap.com/docs/4.0/components/navbar/

Hope this helps.

Best,
Alex
