### ISSUE TITLE
CDN support?

### ISSUE THREAD

**Issue by riklewis** [creativetimofficial/now-ui-kit#43]
Will this great package be available on any CDNs?

**Comment by alexandru-paduraru** [comment]
@riklewis I think we can add it. Do you recommend something?

**Comment by cristijora** [comment]
@alexandru-paduraru if you have the kit on npm it's enough to add a couple of lines in  the `package.json` and it will be available on https://unpkg.com/#/

**Comment by cristijora** [comment]
Actually it is already available,
https://unpkg.com/now-ui-kit@1.0.1/assets/   whole folder

CSS https://unpkg.com/now-ui-kit@1.0.1/assets/css/now-ui-kit.css
JS https://unpkg.com/now-ui-kit@1.0.1/assets/js/

**Comment by alexandru-paduraru** [comment]
@cristijora yes, you're right, I see it there. We will add those links in the readme and description of the project.

**Comment by riklewis** [comment]
Great, thank you.  I was going to suggest MaxCDN as an option (https://www.maxcdn.com), but any CDN is probably better than local hosting :)
