### ISSUE TITLE
Navbar-brand center?

### ISSUE THREAD

**Issue by dylanm21** [creativetimofficial/now-ui-kit#45]
Hey, Just thought i'd see if there is an easy way of making the nav brand centered. I'm trying to add a button on the left, then the nav brand, then the links. I've been messing with it for a while but can't seem to find a simple easy way to do it. Anybody know?

**Comment by alexandru-paduraru** [comment]
@dylanm21 please check this answer: https://stackoverflow.com/questions/33867603/center-an-element-in-bootstrap-4-navbar 

Hope this helps.

Best,
Alex
