### ISSUE TITLE
Nested menus

### ISSUE THREAD

**Issue by Unforgiven-wanda** [creativetimofficial/now-ui-kit#50]
Hello,
it seems impossible to create nested menus, in the nav for example.
Could I trouble you for a fix?

Thank you.

**Comment by alexandru-paduraru** [comment]
@Unforgiven-wanda thank you for using our product. Since the official Bootstrap 4 Beta doesn't support nested menus you need to create your own code, please check this link: https://stackoverflow.com/questions/44467377/bootstrap-4-multilevel-dropdown-inside-navigation

Best,
Alex

**Comment by Unforgiven-wanda** [comment]
Thank you very much. I'll do just that.
