### ISSUE TITLE
npm package out of date

### ISSUE THREAD

**Issue by shunluoifong** [creativetimofficial/now-ui-kit#54]
I did an npm install of the now-ui-kit package, but it installed version 1.0.1. Is there a way to get it upgraded to the latest version?

**Comment by shunluoifong** [comment]
I went ahead and installed directly from github using the following command (I'm using yarn):

`yarn add https://github.com/creativetimofficial/now-ui-kit`

However, when running the gulp task to process the sass files, I get the following error:

```
{ [Error: /Users/username/webdev/sites/sitename/site.css:10355:1: Unknown word  10353 | @import 'now-ui-kit/mixins';
  10354 |
> 10355 | // Plugins CSS
        | ^
  10356 | @import "now-ui-kit/plugins/plugin-bootstrap-switch";
  10357 | @import "now-ui-kit/plugins/plugin-nouislider";]
  message: '/Users/username/webdev/sites/sitename/site.css:10355:1: Unknown word \u001b[90m 10353 | \u001b[39m\u001b[36m@import\u001b[39m \u001b[32m\'now-ui-kit/mixins\'\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 10354 | \u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 10355 | \u001b[39m// Plugins CSS\n \u001b[90m       | \u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 10356 | \u001b[39m\u001b[36m@import\u001b[39m \u001b[32m"now-ui-kit/plugins/plugin-bootstrap-switch"\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 10357 | \u001b[39m\u001b[36m@import\u001b[39m \u001b[32m"now-ui-kit/plugins/plugin-nouislider"\u001b[39m\u001b[33m;\u001b[39m',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-cssnano',
  __safety: { toString: [Function: bound ] } }
```
Seems like the comments in the now-ui-kit.scss file are the issue. And if I remove all the comments in the now-ui-kit.scss file, it gets processed ok...but of course, I don't want to have to edit that file in node_modules/now-ui-kit/.

Any thoughts why this error is getting thrown?

**Comment by alexandru-paduraru** [comment]
Hi @shunluoifong. I've just sent an email to the guy who made our product public on npm to give access so we can update that to v1.1.0 or other future versions. We will see if the problem still persists in v1.1.0 otherwise we will release v1.1.1 with that line removed.

Keep in touch,
Alex

**Comment by amiuhle** [comment]
@alexandru-paduraru Any feedback from him?

**Comment by shunluoifong** [comment]
@alexandru-paduraru Looks like it is still at v1.0.1 on npm. I upgraded to the pro version, so the public npm version isn't as relevant to me now, but I'm sure others would appreciate the ability to get the latest version via npm.

**Comment by alexandru-paduraru** [comment]
@amiuhle and @shunluoifong I've got access to the repo on npmjs: https://www.npmjs.com/package/now-ui-kit but sincerely I don't know how to update it. I've never done that. Any help?

**Comment by amiuhle** [comment]
You need to add a `package.json` to the project and then use `npm publish`. I can create a PR when I'm working on the project again where we're using this. Should be some time later this week.

**Comment by lostncg** [comment]
@alexandru-paduraru the package was outdated (v1.1.0), can you publish the latest version?

**Comment by dragosct10** [comment]
Hi, @lostncg! Thank you for using our products. This product will be published on npm with the latest version. Regards, Dragos
