### ISSUE TITLE
input and button, looks very bad

### ISSUE THREAD

**Issue by ztvMark** [creativetimofficial/now-ui-kit#55]
bug with input and button, looks very bad

https://imgur.com/a/SQ31i

`<div class="input-group"> <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for..."> <span class="input-group-btn"> <button class="btn btn-secondary" type="button">Go!</button> </span> </div> `

**Comment by leandr0magalhaes** [comment]
I have the same issue, the problem is with the input-group-btn
