### ISSUE TITLE
Date-picker sticking

### ISSUE THREAD

**Issue by thebetternewt** [creativetimofficial/now-ui-kit#59]
The date-picker for now-ui-kit looks great, as do the date-pickers in all of your themes. However, in the Now-UI kit, it sticks after picking a date and will not let the user immediately select another date. The user has to click off and back onto the date-picker several times to get the picker to register the new date. Seems like this should be a simple fix hopefully? Once again, love the theme! Good work.

**Comment by dragosct10** [comment]
Hi, @thebetternewt! Thank you for using our product and sorry for the late response. If you want to fix this issue please take the uploaded scss partial and go in `assets/sass/now-ui-kit/plugins/_plugin-datepicker.scss` and replace with the new one. After that please compile your scss with [Koala](koala-app.com) and please be sure that your output is `assets/css/now-ui-kit.css`.
[_plugin-datepicker.scss.zip](https://github.com/creativetimofficial/now-ui-kit/files/1526594/_plugin-datepicker.scss.zip)

Regards,
Dragos

**Comment by poxxac** [comment]
Hi, I have the same issue, and Koala link is broken and no clue how to do all that to fix it :(

**Comment by thebetternewt** [comment]
Dragos,

Thanks, this worked for me! (Sorry for the HUGELY late reply). I am using Rails, so I was able to import the .scss file directly.

------------------------
Chris Eady
P: 662-341-6677
E: chris@starkvilletech.com
