### ISSUE TITLE
NPM/Bower support

### ISSUE THREAD

**Issue by webdevsuperfast** [creativetimofficial/now-ui-kit#6]
Awesome release, could you add support to npm/bower package managers. Thanks!

**Comment by smargovsky** [comment]
`npm install https://github.com/creativetimofficial/now-ui-kit`

**Comment by alexandru-paduraru** [comment]
@webdevsuperfast thank you for the suggestion. Yes, we will add it on the NPM packages soon.

Best,
Alex

**Comment by pi0** [comment]
Hey there awesome work :) Just wonder that is [now-ui-kit](https://www.npmjs.com/package/now-ui-kit) your official release?

**Comment by alexandru-paduraru** [comment]
@pi0 yes, that was added by one of our customers. Is there something wrong with it?

**Comment by pi0** [comment]
Just wanted to make sure it will be updated with latest changes as package.json was not here :))) currently will use git as a dependecy. Thanks for the info :)
