### ISSUE TITLE
Input group addons not working with latest Bootstrap

### ISSUE THREAD

**Issue by pdrlps** [creativetimofficial/now-ui-kit#63]
Check the screenshot, the latest Bootstrap release (4.0.0.beta3) breaks your cute input groups.

![screen shot 2018-01-12 at 12 45 36](https://user-images.githubusercontent.com/210283/34875764-8f4ce85a-f796-11e7-9723-f6dd94206d77.png)

**Comment by dragosct10** [comment]
Hi, @pdrlps! Thank you for using our product. Yes, it is possible that in the beta 3 version multiple things will break, so we will make an update very soon. 

Regards,
Dragos

**Comment by sfaujour** [comment]
The problem is that the class "input-group-addon" isn't anymore implemented in bootstrap 4 final, therefore all the addons aren't working anymore correctly.

**Comment by baldmike** [comment]
This was closed a year ago, I just purchased the kit and it's still an issue.
