### ISSUE TITLE
Input states break when input has label

### ISSUE THREAD

**Issue by gpressutto5** [creativetimofficial/now-ui-kit#66]
![image](https://user-images.githubusercontent.com/12385501/35179001-717ea830-fd78-11e7-9126-bf34038400c9.png)

```html
<div class="form-group has-danger">
    <label for="email">E-mail</label>
    <input type="email" class="form-control" id="email" placeholder="E-mail">
</div>
```

**Comment by dragosct10** [comment]
Hi, @gpressutto5! Thank you for using our product. Please add on the input class alongside class .form-control, the class .form-control-danger and see if the input will work after that. Please let us know if everything is working fine! 

Regards,
Dragos

**Comment by gpressutto5** [comment]
@dragosct10 the class `form-control-danger` changed nothing

**Comment by dragosct10** [comment]
Hi, @gpressutto5! Please, can you give me your link project to see what happened there? Regards, Dragos
