### ISSUE TITLE
Select input breaking 

### ISSUE THREAD

**Issue by wapnen** [creativetimofficial/now-ui-kit#69]
![capture](https://user-images.githubusercontent.com/18328614/36790544-7727e9c2-1c95-11e8-9845-20fd3150c7af.PNG)
hello the select tag looks like this 

the code : 
<div class="input-group form-group-no-border input-lg ">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_email-85"></i>
                                </span>
                                <select class="form-control " name="module" required>
                                    <option disabled="" selected="">Select module</option>
                                    <option value="Use me">Use me</option>
                                    <option value="Writing center">Writing center</option>
                                    <option value="Health">Health</option>
                                </select>

                               
                            </div>

**Comment by dragosct10** [comment]
Hi, @wapnen! Thank you for using our product. Please, can you tell us where did you find this error on which browser? Regards, Dragos
