### ISSUE TITLE
White space on rigth and footer side IE

### ISSUE THREAD

**Issue by asanchezmx** [creativetimofficial/now-ui-kit#70]
Anyone have a solution for this?
![error_ie](https://user-images.githubusercontent.com/36895788/36859239-54ac63a6-1d43-11e8-8a17-b1b2c76c50af.JPG)

It´s on Internet Explorer, I tried adding
html, body { width: 100%; height: 100%; margin: 0px; padding: 0px; overflow-x: hidden; } 
But just work on right side after scrolling.

Thanks.

**Comment by dragosct10** [comment]
Hi @asanchezmx! Have you lateral scroll on IE? Regards, Dragos

**Comment by asanchezmx** [comment]
Hi @dragosct10 no I have not, in Chrome or Firefox it´s ok (full screen) no white spaces anywhere but just in IE doesn´t function like that, and it's just happening when I resize the window. Doesn´t affect functionality but exist a way to patch or solve this issue?

**Comment by dragosct10** [comment]
Hi, @asanchezmx! We will check this and we will come back with an answer. Regards, Dragos
