### ISSUE TITLE
Non-standard MIT License

### ISSUE THREAD

**Issue by jhabdas** [creativetimofficial/now-ui-kit#74]
Thanks for creating this theme. Looks like it's already inspired many to create remixes of the work. One thing I noticed while reviewing the repo was GitHub wasn't showing the license in the normal location. Upon inspection I believe it's occurring because the theme is using a non-standard MIT license.

In particular, this line appears in the license file:

```Designed by Invision (https://www.invisionapp.com). Coded by Creative Tim (https://www.creative-tim.com/)```

The intent here seems to be FOSS. But with the above line in the license file it's not clear if those building upon or remixing this work are supposed to copy that line with the LICENSE (which would make it not MIT). Mind removing that line from the license file so it's standard MIT? Thanks.

**Comment by alexandru-paduraru** [comment]
@jhabdas thank you for letting us know about this. Unfortunately, we need to keep those details in the License as this is the deal that we have with Invision. If we move the line on the line with the copyright, should that follow a standard MIT License? The product is for sure FOSS and our intention is to give it for free and let people work on top of it without any issues (this thing is already happening with over 40.000 people using it).

Best,
Alex

**Comment by jhabdas** [comment]
@alexandru-paduraru thanks for the note. as I understand it you can pretty much do whatever you want with the copyright line. there is a pseudo template sort of thing to it AFIAK but if you wanted to, for example, drop in a BTC/BCH address that's totally acceptable as long as no other lines are added.

If you want a more definitive answer without much effort may I point you to: https://opensource.stackexchange.com/. Thanks for the info.

**Comment by alexandru-paduraru** [comment]
@jhabdas just added it on the same line and now it appears as MIT License in the repo too. Thank you for the details!
