### ISSUE TITLE
NPM Update

### ISSUE THREAD

**Issue by DJSADERS** [creativetimofficial/now-ui-kit#79]
Hi,

When are you going to release 1.2.0 onto NPM?

https://www.npmjs.com/package/now-ui-kit

Thanks

**Comment by dragosct10** [comment]
Hi, @DJSADERS! Thank you for using our products. We will add on npm these days the latest version of the product. 

Regards, 
Dragos

**Comment by UisgeBeatha436** [comment]
Hi,

NPM still has v 1.1.0 of the Now-UI kit. When can we expect an update to the latest version?

Thanks!

**Comment by PaulMaly** [comment]
@dragosct10 Hi! Any chance to upgrade npm version in the near future? Seems it still 1.1.0 instead of 1.3.0.

**Comment by dragosct10** [comment]
Hi, @PaulMaly! Thank you for using our products. Please, check now the npm because it's updated now. 

Regards, 
Dragos

**Comment by PaulMaly** [comment]
@dragosct10 Thanks!
