### ISSUE TITLE
Upwards dropdown

### ISSUE THREAD

**Issue by Wqrld** [creativetimofficial/now-ui-kit#83]
Upwards dropdown
Is it possible to create a dropdown which goes above the text instead of below? I want to have a dropdown on my footer but it will currently only go down.

**Comment by dragosct10** [comment]
Hi, @Wqrld! Thank you for using our products. You can use [dropup](https://getbootstrap.com/docs/4.1/components/dropdowns/#dropup) to do this.  

Regards, 
Dragos

**Comment by Wqrld** [comment]
already found out, just as a suggestion the arrow on the dropup is still wrong when using "dropup"

**Comment by dragosct10** [comment]
Hi! Yes, you're right. This is the free product so the dropup style it's available on the pro version and now you have to style by yourself if you want to put the arrow on the bottom when you have dropup. Thank you for your understanding! Regards, Dragos
