### ISSUE TITLE
Parallax on page header broken on mobile

### ISSUE THREAD

**Issue by fruitcoder** [creativetimofficial/now-ui-kit#89]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
When loading the web page on a mobile device I expect the page header image parallax to work if `data-parallax="true"` is set. However, it stays static. 

# Current Behavior
The image stays still during scroll.

# Failure Information (for bugs)
Tested on iOS and MacOS.

## Steps to Reproduce
Open https://demos.creative-tim.com/now-ui-kit/index.html on an iPhone OR make the Safari window on macOS small to simulate the smallest breakpoint. When the page was open on a large breakpoint before then shrinking the window shows the page like it should be → parallax working. When reloading the page while in the smallest breakpoint the parallax is not working.

**Comment by dragosct10** [comment]
Hi, @fruitcoder! Thank you for using our products. This it's not an issue, we put intentionally for the displays smaller than 992px to block the parallax. You can remove this from the `assets/js/now-ui-kit.js`.

Regards,
Dragos

**Comment by fruitcoder** [comment]
Oh thanks so much for the quick response! And thanks for this amazing Kit
