### ISSUE TITLE
Issue with creative-tim.com site - which does not have its own issue tracker, or so it seems...

### ISSUE THREAD

**Issue by Yetangitu** [creativetimofficial/now-ui-kit#9]
This issue might not have anything to do with the Now UI kit, then again it might. This is what I was met by when opening my account page the very first time:

![image](https://user-images.githubusercontent.com/2754838/26983307-a3e7d1b8-4d3b-11e7-9a4a-8683679ab9bf.png)

Something's hiding under that bar...

Results obtained with Chromium "58.0.3029.96 built on Debian 9.0, running on Debian 9.0
" (according to 'About Chromium')

**Comment by alexandru-paduraru** [comment]
@Yetangitu thank you for the information. It seems there is an issue with the z-indexes on that page. We recently made some changes and it seems we didn't cover that. We will fix it in the next update.

Best,
Alex
