### ISSUE TITLE
Where can I find window title ?

### ISSUE THREAD

**Issue by sam0910** [creativetimofficial/now-ui-kit#90]
It is so strange to ask, but I could not find the site title name.
I am using pro version of Vue Now UI,
I cannot modify the default window title, that is "Vue Now UI Kit PRO - Premium Vue.js UI Kit for Bootstrap".
I did 
```
> find . | grep -r 'Premium Vue.js UI Kit for Bootstrap'
```
and look for it all over the file tree under /src . 

Please help the poor question.

**Comment by dragosct10** [comment]
Hi, @sam0910! Thank you for using our products. Please open the issue on the right [repo](https://github.com/creativetimofficial/vue-now-ui-kit), you're on the HTML version of this product repo. Regards, Dragos
