### ISSUE TITLE
Social Media icons in IndexNavbar don't show. 

### ISSUE THREAD

**Issue by chrisjakuta** [creativetimofficial/now-ui-kit#94]
The social media icons in the `IndexNavbar` reduce in size from 43x43 px to 43x23 px approximately. How can I fix this? 

<img width="1440" alt="Screen Shot 2019-12-03 at 6 48 56 PM" src="https://user-images.githubusercontent.com/30093831/70102405-a1949580-15fd-11ea-965f-b4a791842b6b.png">

**Comment by dragosct10** [comment]
Hi, @chrisjakuta! Thank you for using our products. Please open the issue on the right repo Github, because you're using the React version of the product. This is the link https://github.com/creativetimofficial/now-ui-kit-react. 

Regards, 
Dragos
